### ISSUE TITLE
0.3.0 crashing against 1.0.0-alpha04 with No static method CoilImage

### ISSUE THREAD

**Issue by itsyourapp** [chrisbanes/accompanist#107]
Hi, I am using the latest 0.3.0 of this library with Jetpack Compose 1.0.0-alpha03. I am using the CoilImage function. I get the following crash when I run the application. Code flow does reach the actual CoilImage function call itself (the issue is deeper). 

`2020-10-01 14:25:55.082 15001-15001/app.itsyour.itsyournutrition E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.itsyour.itsyournutrition, PID: 15001
    java.lang.NoSuchMethodError: No static method CoilImage(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Landroidx/compose/ui/Alignment;Landroidx/compose/ui/layout/ContentScale;Landroidx/compose/ui/graphics/ColorFilter;Lkotlin/jvm/functions/Function3;Lkotlin/jvm/functions/Function3;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function1;Landroidx/compose/runtime/Composer;II)V in class Ldev/chrisbanes/accompanist/coil/CoilKt; or its super classes (declaration of 'dev.chrisbanes.accompanist.coil.CoilKt' appears in /data/app/~~hZq07ZuSRRmAHYpqOVfFBw==/app.itsyour.itsyournutrition-kT_xgZ6y7k-HH0onnTZ1Pg==/base.apk!classes13.dex)
        at app.itsyour.itsyournutrition.app.ui.NetworkImageKt.NetworkImage-DCd5uiY(NetworkImage.kt:26)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt$CuisineChip$2$1$1.invoke(CuisineSetting.kt:71)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt$CuisineChip$2$1$1.invoke(Unknown Source:13)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:153)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.foundation.layout.BoxKt$Box$boxChildren$1.invoke(Box.kt:54)
        at androidx.compose.foundation.layout.BoxKt$Box$boxChildren$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.ui.LayoutKt.Layout(Layout.kt:677)
        at androidx.compose.foundation.layout.BoxKt.Box(Box.kt:56)
        at androidx.compose.foundation.layout.BoxKt.Stack(Box.kt:126)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt$CuisineChip$2.invoke(CuisineSetting.kt:70)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt$CuisineChip$2.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:107)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.ui.LayoutKt.Layout(Layout.kt:677)
        at androidx.compose.material.SurfaceKt.SurfaceLayout(Surface.kt:129)
        at androidx.compose.material.SurfaceKt.Surface-biUpMIw(Surface.kt:97)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt.CuisineChip(CuisineSetting.kt:64)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt.CuisineSetting(CuisineSetting.kt:30)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$1$3.invoke(Screen.kt:41)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$1$3.invoke(Unknown Source:13)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:153)
        at androidx.compose.runtime.internal.ComposableLambda$invoke$1.invoke(ComposableLambda.kt:164)
        at androidx.compose.runtime.internal.ComposableLambda$invoke$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScope.compose(Composer.kt:257)
        at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1560)
        at androidx.compose.runtime.Composer.skipToGroupEnd(Composer.kt:1784)
        at androidx.compose.material.ScaffoldKt.Scaffold-tiGujGI(Scaffold.kt:241)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$1.invoke(Screen.kt:33)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$1.invoke(Unknown Source:10)
2020-10-01 14:25:55.082 15001-15001/app.itsyour.itsyournutrition E/AndroidRuntime:     at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScope.compose(Composer.kt:257)
        at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1560)
        at androidx.compose.runtime.Composer.skipToGroupEnd(Composer.kt:1784)
        at androidx.compose.material.SurfaceKt.Surface-biUpMIw(Surface.kt:97)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt.ProfileScreen(Screen.kt:32)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$2.invoke(Unknown Source:6)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$2.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScope.compose(Composer.kt:257)
        at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1560)
        at androidx.compose.runtime.Composer.skipCurrentGroup(Composer.kt:1763)
        at androidx.compose.runtime.Composer.recompose(Composer.kt:1886)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:259)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Unknown Source:0)
        at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$2$2.invoke(Recomposer.kt:199)
        at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$2$2.invoke(Unknown Source:7)
        at androidx.compose.runtime.dispatch.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.kt:34)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.kt:111)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher.access$performFrameDispatch(Unknown Source:0)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.kt:71)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

If I drop the version down to 0.2.0 then I get this crash when the CoilImage function is reached in program flow (the application doesn't crash on startup but instead when the method is actually called). 

`2020-10-01 14:17:32.215 14141-14141/app.itsyour.itsyournutrition E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.itsyour.itsyournutrition, PID: 14141
    java.lang.NoSuchMethodError: No static method CoilImage(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Landroidx/compose/ui/Alignment;Landroidx/compose/ui/layout/ContentScale;Landroidx/compose/ui/graphics/ColorFilter;Lkotlin/jvm/functions/Function3;Lkotlin/jvm/functions/Function3;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function1;Landroidx/compose/runtime/Composer;II)V in class Ldev/chrisbanes/accompanist/coil/CoilKt; or its super classes (declaration of 'dev.chrisbanes.accompanist.coil.CoilKt' appears in /data/app/~~MMh01prcAq4RIusDjlQzkg==/app.itsyour.itsyournutrition-EN1RCfCxNy8nkVBGKyBCDg==/base.apk!classes13.dex)
        at app.itsyour.itsyournutrition.app.ui.NetworkImageKt.NetworkImage-DCd5uiY(NetworkImage.kt:26)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt$CuisineChip$2$1$1.invoke(CuisineSetting.kt:71)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt$CuisineChip$2$1$1.invoke(Unknown Source:13)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:151)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.foundation.layout.StackKt$Stack$stackChildren$1.invoke(Stack.kt:54)
        at androidx.compose.foundation.layout.StackKt$Stack$stackChildren$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.ui.LayoutKt.Layout(Layout.kt:675)
        at androidx.compose.foundation.layout.StackKt.Stack(Stack.kt:56)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt$CuisineChip$2.invoke(CuisineSetting.kt:70)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt$CuisineChip$2.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:107)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.ui.LayoutKt.Layout(Layout.kt:675)
        at androidx.compose.material.SurfaceKt.SurfaceLayout(Surface.kt:129)
        at androidx.compose.material.SurfaceKt.Surface-biUpMIw(Surface.kt:97)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt.CuisineChip(CuisineSetting.kt:64)
        at app.itsyour.itsyournutrition.feature.profile.ui.settings.CuisineSettingKt.CuisineSetting(CuisineSetting.kt:30)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$1$3.invoke(Screen.kt:41)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$1$3.invoke(Unknown Source:13)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:151)
        at androidx.compose.runtime.internal.ComposableLambda$invoke$1.invoke(ComposableLambda.kt:160)
        at androidx.compose.runtime.internal.ComposableLambda$invoke$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScope.compose(Composer.kt:257)
        at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1556)
        at androidx.compose.runtime.Composer.skipToGroupEnd(Composer.kt:1776)
        at androidx.compose.material.ScaffoldKt.Scaffold-tiGujGI(Scaffold.kt:241)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$1.invoke(Screen.kt:33)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:142)
2020-10-01 14:17:32.216 14141-14141/app.itsyour.itsyournutrition E/AndroidRuntime:     at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScope.compose(Composer.kt:257)
        at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1556)
        at androidx.compose.runtime.Composer.skipToGroupEnd(Composer.kt:1776)
        at androidx.compose.material.SurfaceKt.Surface-biUpMIw(Surface.kt:97)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt.ProfileScreen(Screen.kt:32)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$2.invoke(Unknown Source:6)
        at app.itsyour.itsyournutrition.feature.profile.ui.ScreenKt$ProfileScreen$2.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScope.compose(Composer.kt:257)
        at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1556)
        at androidx.compose.runtime.Composer.skipCurrentGroup(Composer.kt:1755)
        at androidx.compose.runtime.Composer.recompose(Composer.kt:1878)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:259)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Unknown Source:0)
        at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$2$2.invoke(Recomposer.kt:199)
        at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$2$2.invoke(Unknown Source:7)
        at androidx.compose.runtime.dispatch.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.kt:34)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.kt:111)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher.access$performFrameDispatch(Unknown Source:0)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.kt:71)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

**Comment by itsyourapp** [comment]
Fixed by upgrading compose to 1.0.0-alpha04

**Comment by vincent-paing** [comment]
I'm still having this issue on compose 1.0.0-alpha 7 and accompanist version 0.3.3.1
